---
title: "Week6B_Lab"
author: "Kevin Candray"
date: "3/3/2021"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: journal 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=TRUE, warning=FALSE,
                      fig.path = "../Output/")
```

# Intro
This is my homework assignment, using the chem data from week 4 and making a plot using **R markdown**.

# Load the Libs
```{r}
library(tidyverse)
library(here)
library(kableExtra)
```

# Loading the data 
```{r}
ChemData <- read_csv(here("Week_4","Data","chemicaldata_maunalua.csv"))
View(ChemData)

```

# Data Wrangling
```{r}
ChemData_sqkey <- ChemData %>% 
  filter(complete.cases(.)) %>% 
  separate(col = Tide_time,
           into = c("Tide","Time"),
           sep = "_") %>% 
  rename("Nitrate + Nitrite (umol/L)" = "NN", #change name of variables
         "Percent SGD" = "percent_sgd",
         "Total Alkylinity (umol/L)" = "TA",
         "Temperature (C)" = "Temp_in",
         "Phosphate (umol/L)" = "Phosphate",
         "Silicate (umol/L)" = "Silicate") %>%
  pivot_longer(cols = c("Temperature (C)", "Phosphate (umol/L)":"Percent SGD"), #pivot to long format
               names_to = "Variables", #one column for all the variable names
               values_to =  "Values") %>% #one column for the values
  mutate(Site = ifelse(Site == "BP", "Black Point", "Wailupe")) # rename sites
View(ChemData_sqkey)
```

# Making a Plot 
```{r ChemFig, fig.width=9, fig.height=6, fig.align="center"}
ggplot(data = ChemData_sqkey, #use ChemData_sqkey
       aes(x = Salinity, #put salinity on x axis
           y = Values, #put values of each variable on y axis
           color = Site)) + #color by site
  geom_jitter() + #make it a jitter graph
  theme_bw() +
  theme(legend.position = c(0.63, 0.15), #move legend into empty space
        legend.background = element_blank(), 
        plot.margin = margin(60, 60, 30, 30)) + #put margin around plot
  facet_wrap(~Variables, scales = "free") + #make one plot for each variable
  labs(y = " ") #remove redundant y label
```

# Making a table
```{r}
ChemData_sqkey %>% 
  group_by(Site) %>% 
  summarise(salinityavg = mean(Salinity, na.rm = TRUE)) %>% 
  kbl() %>% #makes a formatted table
  kable_classic() %>% 
  row_spec(2, bold = T, color = "white", background = "#97CFAE")
```
